### ISSUE TITLE
XMLHttpRequest is not defined

### ISSUE THREAD

**Issue by mariusrak** [oracle/oci-typescript-sdk#160]
I'm trying to upload a file according to [an example](https://github.com/oracle/oci-typescript-sdk/blob/master/examples/javascript/objectstorage.js#L73). But the `oci-common` uses the browser implementation of fetch pollyfil instead of node implementation and hence I get the error
```
ReferenceError: XMLHttpRequest is not defined
    at C:\...\node_modules\whatwg-fetch\dist\fetch.umd.js:514:17
    at new Promise (<anonymous>)
    at fetch (C:\...\node_modules\whatwg-fetch\dist\fetch.umd.js:507:12)
    at Function.<anonymous> (C:\...\node_modules\oci-common\lib\circuit-breaker.js:23:40)
    at Generator.next (<anonymous>)
    at C:\...\node_modules\oci-common\lib\circuit-breaker.js:12:71
    at new Promise (<anonymous>)
    at __awaiter (C:\...\node_modules\oci-common\lib\circuit-breaker.js:8:12)
    at C:\...\node_modules\oci-common\lib\circuit-breaker.js:21:49
    at new Promise (<anonymous>)
    at Function.<anonymous> (C:\...\node_modules\oci-common\lib\circuit-breaker.js:21:16)
    at Generator.next (<anonymous>)
    at C:\...\node_modules\oci-common\lib\circuit-breaker.js:12:71
    at new Promise (<anonymous>)
    at __awaiter (C:\...\node_modules\oci-common\lib\circuit-breaker.js:8:12)
    at Function.FetchWrapper (C:\...\node_modules\oci-common\lib\circuit-breaker.js:20:12)
    at C:\...\node_modules\opossum\lib\circuit.js:521:38
    at new Promise (<anonymous>)
    at CircuitBreaker.call (C:\...\node_modules\opossum\lib\circuit.js:497:12)
    at CircuitBreaker.fire (C:\...\node_modules\opossum\lib\circuit.js:415:22)
    at FetchHttpClient.<anonymous> (C:\...\node_modules\oci-common\lib\http.js:76:26)
    at Generator.next (<anonymous>)
    at fulfilled (C:\...\node_modules\oci-common\lib\http.js:28:58)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
```

**Comment by mariusrak** [comment]
Sorry, my problem - conflict in packages
