### ISSUE TITLE
ENOENT uuid node package

### ISSUE THREAD

**Issue by mariusrak** [oracle/oci-typescript-sdk#169]
Hi. I am getting randomly this error. But the file exists. I tried `cat /usr/src/app/.../node_modules/oci-common/node_modules/uuid/v1.js` and content was there. The error appear after I rebuild and reload application.

```
Error: ENOENT: no such file or directory, open '/usr/src/app/.../node_modules/oci-common/node_modules/uuid/v1.js'
    at Object.openSync (node:fs:590:3)
    at Object.readFileSync (node:fs:458:35)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1172:18)
    at Module.load (node:internal/modules/cjs/loader:1033:32)
    at Function.Module._load (node:internal/modules/cjs/loader:868:12)
    at Module.require (node:internal/modules/cjs/loader:1057:19)
    at require (node:internal/modules/cjs/helpers:103:18)
    at Object.<anonymous> (/usr/src/app/.../node_modules/oci-common/lib/headers.js:11:16)
    at Module._compile (node:internal/modules/cjs/loader:1155:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1209:10)
    at Module.load (node:internal/modules/cjs/loader:1033:32)
    at Function.Module._load (node:internal/modules/cjs/loader:868:12)
    at Module.require (node:internal/modules/cjs/loader:1057:19)
    at require (node:internal/modules/cjs/helpers:103:18)
    at Object.<anonymous> (/usr/src/app/.../node_modules/oci-common/lib/helper.js:19:19)
    at Module._compile (node:internal/modules/cjs/loader:1155:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1209:10)
    at Module.load (node:internal/modules/cjs/loader:1033:32)
    at Function.Module._load (node:internal/modules/cjs/loader:868:12)
    at Module.require (node:internal/modules/cjs/loader:1057:19)
    at require (node:internal/modules/cjs/helpers:103:18)
    at Object.<anonymous> (/usr/src/app/.../node_modules/oci-common/lib/signer.js:17:18)
    at Module._compile (node:internal/modules/cjs/loader:1155:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1209:10)
    at Module.load (node:internal/modules/cjs/loader:1033:32)
    at Function.Module._load (node:internal/modules/cjs/loader:868:12)
    at Module.require (node:internal/modules/cjs/loader:1057:19)
    at require (node:internal/modules/cjs/helpers:103:18)
    at Object.<anonymous> (/usr/src/app/.../node_modules/oci-common/index.js:32:29)
    at Module._compile (node:internal/modules/cjs/loader:1155:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1209:10)
    at Module.load (node:internal/modules/cjs/loader:1033:32)
    at Function.Module._load (node:internal/modules/cjs/loader:868:12)
    at Module.require (node:internal/modules/cjs/loader:1057:19)
    at require (node:internal/modules/cjs/helpers:103:18)
    at Object.<anonymous> (/usr/src/app/.../node_modules/oci-objectstorage/lib/client.js:47:16)
    at Module._compile (node:internal/modules/cjs/loader:1155:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1209:10)
    at Module.load (node:internal/modules/cjs/loader:1033:32)
    at Function.Module._load (node:internal/modules/cjs/loader:868:12)
    at Module.require (node:internal/modules/cjs/loader:1057:19)
    at require (node:internal/modules/cjs/helpers:103:18)
    at Object.<anonymous> (/usr/src/app/.../node_modules/oci-objectstorage/index.js:44:29)
    at Module._compile (node:internal/modules/cjs/loader:1155:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1209:10)
    at Module.load (node:internal/modules/cjs/loader:1033:32)
    at Function.Module._load (node:internal/modules/cjs/loader:868:12)
    at Module.require (node:internal/modules/cjs/loader:1057:19)
    at require (node:internal/modules/cjs/helpers:103:18)
    at Object.55753 (eval at run (/usr/src/app/.../Engine/UserServer.js:56:25), <anonymous>:432:20349)
    at n (eval at run (/usr/src/app/.../Engine/UserServer.js:56:25), <anonymous>:432:1248067)
    at Object.36754 (eval at run (/usr/src/app/.../Engine/UserServer.js:56:25), <anonymous>:432:86497)
    at n (eval at run (/usr/src/app/.../Engine/UserServer.js:56:25), <anonymous>:432:1248067)
    at eval (eval at run (/usr/src/app/.../Engine/UserServer.js:56:25), <anonymous>:432:1248583)
    at eval (eval at run (/usr/src/app/.../Engine/UserServer.js:56:25), <anonymous>:432:1248593)
    at UserServer.run (/usr/src/app/.../Engine/UserServer.js:56:25)
    at Engine.startUserServer (/usr/src/app/.../Engine/index.js:395:42)
    at Engine.restartApp (/usr/src/app/.../Engine/index.js:334:28)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (node:internal/process/task_queues:96:5) {
  errno: -2,
  syscall: 'open',
  code: 'ENOENT',
  path: '/usr/src/app/.../node_modules/oci-common/node_modules/uuid/v1.js'
}
```

**Comment by waruwaruwaru** [comment]
Hi @mariusrak what version of the SDK are you using? Can you also provide the steps to reproduce this error? I created a project and `npm install oci-sdk `and did not get this issue. Let me know how I can reproduce it. Thanks!

**Comment by waruwaruwaru** [comment]
I have not heard back and will be closing this ticket. If this is still an issue, please feel free to re-open it again.
