### ISSUE TITLE
oci-objectstorage Upload Manager doesn't work with large files

### ISSUE THREAD

**Issue by nicholasgiles** [oracle/oci-typescript-sdk#90]
Follow up from issue: https://github.com/oracle/oci-typescript-sdk/issues/50

This library is still not useable for us for uploading files to object storage, as it appears that the entire file is being loaded into memory, which causes problems for large files. For example, a 1.5G file causes the Node process to be killed with an out of memory error.

Here is my test code:
```
const storageClient = new OciObjectStorage.ObjectStorageClient({
  authenticationDetailsProvider: new OciCommon.SimpleAuthenticationDetailsProvider(
    config.OBJECT_STORAGE.TENANCY,
    config.OBJECT_STORAGE.USER_ID,
    config.OBJECT_STORAGE.FINGERPRINT,
    config.OBJECT_STORAGE.PRIVATE_KEY,
    undefined, // no passphrase
    OciCommon.Region.fromRegionId(config.OBJECT_STORAGE.REGION)
  ),
});

const uploadManager = new OciObjectStorage.UploadManager(storageClient);

uploadManager.upload({
  content: {
    filePath: '/tmp/file.bin',
  },
  requestDetails: {
    namespaceName: config.OBJECT_STORAGE.NAMESPACE,
    bucketName: 'dev',
    objectName: 'exports/file.bin',
  },
}).then((value) => {
  console.log(value);
});
```

This results in high memory usage for the process (which looks like the whole file is being loaded into memory), and the following error message:
```
error from defaultErrorFunction:  Error: Timed out after 10000ms
    at buildError (/opt/skulk/node_modules/opossum/lib/circuit.js:699:17)
    at Timeout.<anonymous> (/opt/skulk/node_modules/opossum/lib/circuit.js:504:29)
    at listOnTimeout (internal/timers.js:555:17)
    at processTimers (internal/timers.js:498:7) {
  code: 'ETIMEDOUT',
  [Symbol(our-error)]: true
}
Request failed with Exception : Error: Timed out after 10000ms
```

Node.js version: 14.17.0
oci-typescript-sdk version: 2.1.0

**Comment by jodoglevy** [comment]
@nicholasgiles thanks for reporting - we'll take a look

**Comment by y-chandra** [comment]
@nicholasgiles - Which version of the SDK are you using? Can you please use the latest version of the SDK - `version 2.2.0` and try the API again?

**Comment by nicholasgiles** [comment]
@y-chandra Similar behavior with v2.2.0; results:

```
bash-4.2# node --version
v14.17.0
bash-4.2# grep version node_modules/oci-objectstorage/package.json
  "version": "2.2.0",
bash-4.2# node os_test.js
Killed
```

Seen using "top" command:
```
top - 18:46:44 up 22 days,  1:50,  0 users,  load average: 1.17, 1.43, 1.20
Tasks:  19 total,   2 running,  17 sleeping,   0 stopped,   0 zombie
%Cpu(s):  2.8 us,  1.9 sy,  0.0 ni, 95.1 id,  0.1 wa,  0.0 hi,  0.1 si,  0.0 st
KiB Mem :  5057056 total,   121396 free,  3617292 used,  1318368 buff/cache
KiB Swap:  4194300 total,   957660 free,  3236640 used.   156536 avail Mem

  PID USER      PR  NI    VIRT    RES    SHR S  %CPU %MEM     TIME+ COMMAND
 2722 root      20   0 4084672   2.4g  17908 S   0.0 49.3   0:42.65 node os_test.js
```
showing that the memory usage is huge, presumably because it's attempting to load the entire file into memory.

**Comment by y-chandra** [comment]
We're still looking into fixing the issue, as a workaround, can you please use the version `1.19.5` and try uploading the file?

**Comment by nicholasgiles** [comment]
@y-chandra Why is the behavior in version `1.19.5` likely to be different from the three other versions I've previously tested?

As far as I can see, there is a design flaw in the library that causes it to buffer the entire contents of a stream into memory before uploading it to object storage so, until this is addressed, I can't see the benefit of testing any further different versions.

**Comment by jodoglevy** [comment]
Hi @nicholasgiles - to provide a bit more context - we think the issue you're hitting was introduced in the version after 1.19.5. When @y-chandra tests v1.19.5, he is able to get a large upload to work, but with later versions, this seems to not work anymore.

We are working on fixing the issue for new versions of the SDK going forward -- @y-chandra 's comment was just meant to provide a workaround you could use if you're blocked right now. If you're not blocked, there's no reason you need to use 1.19.5.

**Comment by nicholasgiles** [comment]
@jodoglevy Thanks for the update.

From my experience (starting with https://github.com/oracle/oci-typescript-sdk/issues/50), this has never worked properly - specifically, there has never been a way to upload large files to OCI OS without those files having to be loaded entirely into memory first.

We have been using the AWS SDK with OCI OS S3 compatibility and, as such, are not blocked but we do want to move away from this and onto the OCI SDK. This issue currently prevents us from achieving this.

**Comment by y-chandra** [comment]
@nicholasgiles  - I tested uploading a large file using UploadManager with version `1.19.5` and the memory usage is significantly less in this version. It seems after this version, we implemented some new features like supporting stream bodies for UploadManager that eventually caused the increase in memory usage. However this would only work if you're using a file to upload.

**Comment by nicholasgiles** [comment]
@y-chandra @jodoglevy I just ran a test with version `1.19.5` and uploading a 1.5GB file, and I concur that it does work a lot better - memory usage never got above ~7%, which is a vast improvement on the ~49% I was seeing with the newer versions of the library.

So I'd say if you can revert the behavior to be similar to that of version `1.19.5` in the next version of the library then we would most likely be happy with that.

**Comment by jodoglevy** [comment]
@nicholasgiles thanks for validating that what we are seeing works for you as well. We'll work on fixing this in the latest versions of the SDK, however it won't be as simple as reverting to the way this was done in 1.19.5, as we need to also not drop stream support, which was added in the version after 1.19.5

**Comment by nicholasgiles** [comment]
@jodoglevy I don't know if the stream support was added in response to https://github.com/oracle/oci-typescript-sdk/issues/50 which I raised (a comment in that ticket indicates the fix was delivered with version `1.20.1`) but from my perspective it didn't work in any case (due to high memory usage), hence why I eventually switched to trying to use the Upload Manager instead.

**Comment by kdclaw3** [comment]
@jodoglevy @y-chandra What is the appropriate channel for getting resolution to this? Should we submit an official Support Request.

**Comment by y-chandra** [comment]
@kdclaw3 - Can you confirm if you're using UploadManager to upload files and if fixing this for files will resolve your issue?

**Comment by kdclaw3** [comment]
@y-chandra Yes we are using upload manager, and have no workaround currently. 1.19.5 wont upload empty files and 2.3.1 wont upload large files.

**Comment by jodoglevy** [comment]
@kdclaw3 what we'd like to better understand is if this is only blocking you for files, or if you also need to upload non-file streams

**Comment by kdclaw3** [comment]
@jodoglevy we are only using it for files.

**Comment by jodoglevy** [comment]
great. @y-chandra  is working on a fix for that use case

**Comment by kdclaw3** [comment]
@waruwaruwaru it is not working for us. Now we are getting a new error. 

1. We have completely emptied the bucket, we have removed all uncommitted multipart uploads.
2. We get this error
`Request cannot be retried. Not Retrying. Exception occurred : Error: The computed MD5 hash (acBf4HGRKHDC1NO/O3QuZQ==) does not match the expected MD5 hash (4r81kp2g5acDaMwPI7WdXA==)
Upload part failed, will retry. Last known error: Error: The computed MD5 hash (acBf4HGRKHDC1NO/O3QuZQ==) does not match the expected MD5 hash (4r81kp2g5acDaMwPI7WdXA==)`
